### PR TITLE
[MIM-787] Mim 787 bump react number format from 4 to 5

### PR DESCRIPTION
**Pull request by johnnadeluy**
[Link to ticket: MIM-787](https://statistics-norway.atlassian.net/browse/MIM-787)

### CODE REVIEW

**Comment by annesiri** [comment]
Ser ikke ut som denne PR-en er koblet til jira-saken? Noen ide om hvorfor?

**Comment by annesiri** [comment]
This might be far fetched, but found a table where also years displays with thousand separator:



Link to this locally: http://localhost:8080/admin/site/preview/default/draft/ssb/sosiale-forhold-og-kriminalitet/kriminalitet-og-rettsvesen/artikler/nar-betingelsene-er-straffen

**Comment by johnnadeluy** [comment]
> This might be far fetched, but found a table where also years displays with thousand separator: Screenshot 2023-11-23 at 15 30 58
> 
> Link to this locally: http://localhost:8080/admin/site/preview/default/draft/ssb/sosiale-forhold-og-kriminalitet/kriminalitet-og-rettsvesen/artikler/nar-betingelsene-er-straffen

Those years don't seem to be included in PROD so it shouldn't pose a problem.

**Comment by johnnadeluy** [comment]
> Ser ikke ut som denne PR-en er koblet til jira-saken? Noen ide om hvorfor?

It seems to have been resolved now!



> This might be far fetched, but found a table where also years displays with thousand separator: Screenshot 2023-11-23 at 15 30 58
> 
> Link to this locally: http://localhost:8080/admin/site/preview/default/draft/ssb/sosiale-forhold-og-kriminalitet/kriminalitet-og-rettsvesen/artikler/nar-betingelsene-er-straffen

Those years don't seem to be included in PROD so it shouldn't pose a problem. Although I can't say with certainty that this won't pose a problem anywhere else. I'm unsure how often years this way in tables.

**Comment by annesiri** [comment]
code looks good!

**Review by annesiri — APPROVED** [review]

**Pull request merged**
